import { Toaster } from "@/components/ui/sonner";
import VLOOProLayoutProvider from "@/components/Layouts/VLOOProLayoutProvider";

export const metadata = {
  title: "VLOOPro Page",
  description: "Generated by VLOOPro Page",
};

export default function VLOOProLayout({ children }) {
  return (
    <main>
      <VLOOProLayoutProvider>
        {children}
        <Toaster position="top-center" richColors />
      </VLOOProLayoutProvider>
    </main>
  );
}
