import PortalLayoutProvider from "@/components/Layouts/PortalLayoutProvider";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Host Portal",
  description: "Generated by VLOO",
};

const PortalLayout = ({ children }) => {
  return (
    <main>
      <PortalLayoutProvider>
        {children}
        <Toaster position="top-center" richColors />
      </PortalLayoutProvider>
    </main>
  );
};

export default PortalLayout;
