import DynamicFavicon from "@/components/HelperFunctions/DynamicFavicon";
import { Barlow } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { AuthProvider } from "@/contexts/AuthContext";

const barlow = Barlow({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-barlow",
});

export const metadata = {
    title: "VLOO",
    description: "Generated by VLOO",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="icon"
                    href="/assets/favicon.ico"
                    sizes="32x32"
                    type="image/png"
                />
                <script
                    async
                    defer
                    src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
                />
            </head>
            <body className={`${barlow.className} bg-red-700`} suppressHydrationWarning>
                <Providers>
                    <AuthProvider>{children}</AuthProvider>
                </Providers>
                <DynamicFavicon />
            </body>
        </html>
    );
}
